# -*- coding: UTF-8 -*-
# -----------------------------------------------------------------------------
#    xierpa server
#    Copyright (c) 2014+  buro@petr.com, www.petr.com, www.xierpa.com
#    
#    X I E R P A  3
#    Distribution by the MIT License.
#
# -----------------------------------------------------------------------------
#
#    make.py
#
#    Demo site for the simple "hello world" example.
#    The "run.py" program creates the files:
#        ~/Xierpa3Examples/HelloWorldLayout/css/style.scss
#        ~/Xierpa3Examples/HelloWorldLayout/css/style.css
#        ~/Xierpa3Examples/HelloWorldLayout/index.html
#    from the one HelloWorldLayout theme instance by applying respectively the
#    CssBuilder and HtmlBuilder to the theme.
#    Each of the builders takes the information from the theme to build its
#    own type of file.
#
import webbrowser
from xierpa3.components import Theme, Page, Column 
from xierpa3.builders.cssbuilder import CssBuilder
from xierpa3.builders.htmlbuilder import HtmlBuilder
from xierpa3.attributes import Em, Margin 
from xierpa3.descriptors.media import Media # Include type of Style that holds @media parameters.
from xierpa3.descriptors.blueprint import BluePrint

class SimpleResponsiveText(Column):

    BLUEPRINT = BluePrint(
        color='yellow', doc_color=u'Column text color.',
        colorTablet='orange', doc_colorTablet=u'Column text color for tablet.',
        colorMobile='red', doc_colorMobile=u'Column text color for mobile.',
    )
    CSS_BODYFONT = 'Georgia'
    CSS_CAPTIONFONT = CSS_BODYFONT
    
    def buildBlock(self, b):
        u"""Build the column. Note that although the "div" suggest that it is just
        HTML building there, the method get called both with <b>b</b> as CssBuilder
        and as HtmlBuilder. Each builder will filter out the appropriate attributes and
        translates it into its own syntax. The HTML tags generated by the article
        are set in CSS by the empty statements.
        Building the styled 2 text blocks, written out with duplicated values,
        as example how this works. See other examples for approaches with more
        cascading styled hierarchy."""
        s = self.style
        b.div(class_='column', color=s.color, margin=Margin(0, self.AUTO), 
            width='80%', maxwidth=700, minwidth=300, backgroundcolor='#222',
            paddingtop=Em(0.5), paddingbottom=Em(0.5), fontfamily=self.CSS_BODYFONT, 
            fontsize=Em(4), textalign=self.CENTER, lineheight=Em(1.2),
            # Now define the @media parameters, where they belong: inside the definition of the element.
            # The media parameters are collected and sorted for output at the end of the CSS document.
            media=(
               # Example for table, show lighter background, change color of text and smaller size.
               Media(min=self.M_TABLET_MIN, max=self.M_TABLET_MAX, backgroundcolor='#444', 
                   color=s.colorTablet, fontsize=Em(3), width=self.C100),
               # For mobile, even more lighter background, change color of text and smaller size.
               Media(max=self.M_MOBILE_MAX, backgroundcolor='#BBB', color=s.colorMobile, 
                   fontsize=Em(2), width=self.C100)
            ))
        b.text('This is a text. ' * 100)
        b._div()
        
class SimpleResponsive(Theme):
    u"""The <b>SimpleResponsive</b> class implements a simple page with a text and an image."""
    TITLE = u'The simple responsive text page.' # Use as title of window.

    def baseComponents(self):
        u"""Create a theme site with just one single template home page. Answer a list
        of page instances that are used as templates for this site."""
        # Create an instance (=object) of the text component to be placed on the page.
        hw = SimpleResponsiveText()
        # Create an instance (=object) of the page, containing the "hw" component.
        homePage = Page(components=(hw,), title=self.TITLE)
        # Answer a list of types of pages for this site.
        return [homePage]

    def make(self):
        u"""Make the instance of this class to build CSS and HTML."""
        # Create an "instance" (=object) of type "HelloWorldLayout". The type (=class) defines
        # the behavior of the object that is made by calling the class.

        # C S S
        # Create the main CSS builder instance to build the CSS part of the site.
        cssBuilder = CssBuilder()
        # Compile (=build) the SCSS to CSS and save the file in "css/style.css".
        cssBuilder.save(self) 
    
        # H T M L
        # Create the main HTML builder instance to build the HTML part of the site.
        htmlBuilder = HtmlBuilder()
        # Compile the HTML and save the resulting HTML file in "helloWorld.html".
        # Answer the path, so we can open the file with a browser.
        return htmlBuilder.save(self)  
    
if __name__ == '__main__':
    # This construction "__name__ == '__main__'" makes this Python file only 
    # be executed when called in direct mode, such as "python make.py" in the terminal.         
    path = SimpleResponsive().make()
    webbrowser.open(path)
